(setq inhibit-startup-screen 1)
(column-number-mode 1)
(global-unset-key "\C-s")
(global-set-key "\C-ss" `isearch-forward)
(global-set-key "\C-cs" `shell)
(global-set-key "\C-sk" `kill-whole-line)
(global-set-key "\C-xra" `append-to-register)
(global-set-key "\C-xrp" `prepend-to-register)
(global-set-key [M-left] 'windmove-left) 
(global-set-key [M-right] 'windmove-right)
(global-set-key [M-up] 'windmove-up) 
(global-set-key [M-down] 'windmove-down)
(autoload 'ansi-color-for-comint-mode-on "ansi-color" nil t)
(add-hook 'shell-mode-hook 'ansi-color-for-comint-mode-on)

(defun my-c-mode-common-hook ()
(c-set-style "Stroustrup")
(linum-mode 1)
(electric-indent-mode t)
(setq c-basic-offset 4)
(setq c-auto-newline 1)
       )
(add-hook 'c-mode-common-hook 'my-c-mode-common-hook)
