(setq inhibit-startup-screen 1)
(global-unset-key "\C-s")
(global-set-key "\C-ss" `isearch-forward)
(global-set-key "\C-cs" `shell)
(global-set-key "\C-sk" `kill-wholee-line)
(defun my-c-mode-common-hook ()
(setq electric-indent-mode 1)
(setq c-basic-offset 4)
(setq c-auto-newline 1)
       )
(add-hook 'c-mode-common-hook 'my-c-mode-common-hook)
